/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AiActivityAction = "analyze" | "apply_suggestion" | "edit" | "generate" | "generate_image" | "memory_update" | "publish" | "qa" | "replicate" | "suggest";

export type AiActivityOutcome = "failure" | "partial" | "rejected" | "success" | "user_edited";

export type AiJobStatus = "cancelled" | "completed" | "failed" | "pending" | "running";

export type AiJobType = "generate_assets" | "generate_page" | "replicate_site" | "run_playbook";

export type AssetGenerationStatus = "analyzing" | "failed" | "generating" | "pending" | "ready" | "uploaded";

export type AssetGenerationUseCase = "b_roll" | "background" | "blog_header" | "hero" | "program_page" | "social";

export type AssetSource = "ai_generated" | "scraped" | "screenshot" | "upload";

export type AssetType = "document" | "font" | "icon" | "image" | "logo" | "video";

export type DeploymentStatus = "building" | "failed" | "pending" | "success";

export type DocSource = "ai_extracted" | "imported" | "manual";

export type DocStatus = "active" | "archived";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MembershipRole = "admin" | "member" | "owner";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PageStatus = "archived" | "draft" | "published";

export type SiteMode = "greenfield" | "replication" | "template";

export type SiteStatus = "archived" | "draft" | "published";

export type ThemeSource = "ai_generated" | "replicated" | "system_preset" | "user_selected";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkspaceStatus = "active" | "cancelled" | "suspended" | "trial";

export interface AiActivity {
  actionType: AiActivityAction;
  aiJobUuid: string | null;
  costUsd: Numeric | null;
  createdAt: Generated<Timestamp>;
  errorMessage: string | null;
  fidelityScore: Numeric | null;
  inputDocKeys: string | null;
  inputTokens: number | null;
  latencyMs: number | null;
  metadata: Json | null;
  model: string | null;
  outcome: AiActivityOutcome;
  outputTokens: number | null;
  promptTemplateKeys: string | null;
  provider: string | null;
  siteUuid: string | null;
  summary: string;
  userCorrection: string | null;
  userUuid: string;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface AiJobs {
  createdAt: Generated<Timestamp>;
  input: Json | null;
  options: Json | null;
  output: Json | null;
  playbookUuid: string | null;
  siteUuid: string | null;
  state: Json | null;
  status: Generated<AiJobStatus>;
  steps: Json | null;
  type: AiJobType;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface AssetGenerations {
  costUsd: Numeric | null;
  createdAt: Generated<Timestamp>;
  failureReason: string | null;
  generatedAssetUuid: string | null;
  metadata: Json | null;
  outputSpec: Json;
  promptSnapshot: Json | null;
  provider: string | null;
  providerJobId: string | null;
  referenceAssetUuids: Json | null;
  retries: Generated<number>;
  siteUuid: string | null;
  status: Generated<AssetGenerationStatus>;
  subject: string;
  updatedAt: Generated<Timestamp>;
  useCase: AssetGenerationUseCase;
  userUuid: string;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface Assets {
  createdAt: Generated<Timestamp>;
  metadata: Json | null;
  mimeType: string | null;
  name: string;
  source: Generated<AssetSource>;
  storageKey: string;
  type: AssetType;
  url: string;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface Deployments {
  artifactUrl: string | null;
  buildId: string;
  createdAt: Generated<Timestamp>;
  metadata: Json | null;
  previewUrl: string | null;
  siteUuid: string;
  status: Generated<DeploymentStatus>;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface Docs {
  content: string | null;
  contentJson: Json | null;
  createdAt: Generated<Timestamp>;
  embedding: string | null;
  key: string;
  siteUuid: string | null;
  source: Generated<DocSource>;
  status: Generated<DocStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface Leads {
  createdAt: Generated<Timestamp>;
  email: string | null;
  fields: Json;
  formId: string;
  ip: string | null;
  name: string | null;
  phone: string | null;
  siteUuid: string;
  sourcePath: string | null;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface LlmModelPricing {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  effectiveFrom: Generated<Timestamp>;
  effectiveUntil: Timestamp | null;
  inputPricePer1kTokens: Numeric;
  metadata: Json | null;
  model: string;
  outputPricePer1kTokens: Numeric;
  provider: string;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface OrganizationMemberships {
  createdAt: Generated<Timestamp>;
  organizationUuid: string;
  role: Generated<MembershipRole>;
  updatedAt: Generated<Timestamp>;
  userUuid: string;
  uuid: Generated<string>;
}

export interface Organizations {
  createdAt: Generated<Timestamp>;
  metadata: Json | null;
  name: string;
  ownerUserUuid: string | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface Pages {
  canonicalUrl: string | null;
  createdAt: Generated<Timestamp>;
  isHomePage: Generated<boolean>;
  metaDescription: string | null;
  metaTitle: string | null;
  ogImageUrl: string | null;
  publishedAt: Timestamp | null;
  robots: string | null;
  schemaJson: Json | null;
  sections: Generated<Json>;
  siteUuid: string;
  slug: string;
  status: Generated<PageStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface PipelineArtifacts {
  createdAt: Generated<Timestamp>;
  payload: Json;
  siteUuid: string;
  stage: string;
  uuid: Generated<string>;
  version: number;
  workspaceUuid: string;
}

export interface Playbooks {
  category: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  inputSchema: Json | null;
  isSystem: Generated<boolean>;
  key: string;
  name: string;
  steps: Generated<Json>;
  thumbnailUrl: string | null;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string | null;
}

export interface Sites {
  cloudfrontDomain: string | null;
  createdAt: Generated<Timestamp>;
  customDomain: string | null;
  defaultMetaDescription: string | null;
  defaultMetaTitle: string | null;
  faviconUrl: string | null;
  integrations: Json | null;
  mirrorStatus: string | null;
  mode: Generated<SiteMode>;
  name: string;
  notifyEmail: string | null;
  ogImageUrl: string | null;
  publishedAt: Timestamp | null;
  schemaJson: Json | null;
  slug: string;
  sourceUrl: string | null;
  status: Generated<SiteStatus>;
  subdomain: string | null;
  themeUuid: string | null;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface SiteTransforms {
  author: Generated<string>;
  createdAt: Generated<Timestamp>;
  ordinal: number;
  pageGlob: string;
  payload: Json;
  selector: string | null;
  siteUuid: string;
  status: Generated<string>;
  type: string;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface SiteVersions {
  createdAt: Generated<Timestamp>;
  deployPrefix: string;
  kind: string;
  label: string | null;
  publishedAt: Timestamp | null;
  siteUuid: string;
  uuid: Generated<string>;
  version: number;
  workspaceUuid: string;
}

export interface Templates {
  category: string | null;
  createdAt: Generated<Timestamp>;
  instructions: string | null;
  isSystem: Generated<boolean>;
  key: string;
  name: string;
  page: Json | null;
  placeholders: Json | null;
  sourceUrl: string | null;
  tags: string[] | null;
  theme: Json | null;
  thumbnailUrl: string | null;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string | null;
}

export interface Themes {
  createdAt: Generated<Timestamp>;
  name: string;
  parentThemeUuid: string | null;
  source: Generated<ThemeSource>;
  templateKey: string | null;
  tokens: Json;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string | null;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  externalUserId: string | null;
  metadata: Json | null;
  name: string | null;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface WorkspaceBrandMemory {
  businessArchetype: string | null;
  businessName: string | null;
  colorPalette: Json | null;
  createdAt: Generated<Timestamp>;
  differentiators: Json | null;
  equipmentTags: Json | null;
  imageryStrategy: string | null;
  interiorAndFinishes: string | null;
  lighting: string | null;
  mood: string | null;
  promptKeywords: Json | null;
  richContext: Json | null;
  signageNotes: string | null;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface WorkspaceMemberships {
  createdAt: Generated<Timestamp>;
  role: Generated<MembershipRole>;
  updatedAt: Generated<Timestamp>;
  userUuid: string;
  uuid: Generated<string>;
  workspaceUuid: string;
}

export interface Workspaces {
  brandFontBody: string | null;
  brandFontHeading: string | null;
  brandPrimaryColor: string | null;
  createdAt: Generated<Timestamp>;
  externalIds: Json | null;
  metadata: Json | null;
  name: string;
  organizationUuid: string | null;
  ownerUserId: string | null;
  slug: string;
  status: Generated<WorkspaceStatus>;
  updatedAt: Generated<Timestamp>;
  uuid: Generated<string>;
}

export interface DB {
  aiActivity: AiActivity;
  aiJobs: AiJobs;
  assetGenerations: AssetGenerations;
  assets: Assets;
  deployments: Deployments;
  docs: Docs;
  leads: Leads;
  llmModelPricing: LlmModelPricing;
  organizationMemberships: OrganizationMemberships;
  organizations: Organizations;
  pages: Pages;
  pipelineArtifacts: PipelineArtifacts;
  playbooks: Playbooks;
  sites: Sites;
  siteTransforms: SiteTransforms;
  siteVersions: SiteVersions;
  templates: Templates;
  themes: Themes;
  users: Users;
  workspaceBrandMemory: WorkspaceBrandMemory;
  workspaceMemberships: WorkspaceMemberships;
  workspaces: Workspaces;
}
