// Auto-generated by milo template pipeline — review and enrich before shipping.
import type { TemplateSpec } from "./types.js";

export const modernSpec: TemplateSpec = {
  name: "modern",
  description: "Auto-generated from modern reference site.",
  headAssets: [
    { tag: "link", attrs: { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800;900&family=Barlow:wght@400;600;700&display=swap" } },
    { tag: "link", attrs: { rel: "stylesheet", href: "/styles/modern.css" } },
  ],
  bodyClasses: ["bg-white"],
  sections: {},
  components: {
    "Unknown": {
      component: "Unknown",
      purpose: "unknown — unknown layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} }
      },
    },
    "FeatureGridEven": {
      component: "FeatureGridEven",
      purpose: "content-block — feature-grid-even layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"features"} }
      },
    },
    "HeroCenter": {
      component: "HeroCenter",
      purpose: "hero — hero-center layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "subheadline": { purpose: "Supporting subtitle text", type: "string", required: false, guidance: "1-2 sentences, expand on the headline", example: "Join our community and reach your goals.", source: {"kind":"pageField","path":"hero.subheading"} },
        "ctaText": { purpose: "Call-to-action button label", type: "string", required: false, guidance: "2-4 words, imperative verb, low commitment", example: "Book a free class", source: {"kind":"pageField","path":"hero.ctaLabel"} },
        "ctaHref": { purpose: "Call-to-action button URL", type: "string", required: false, guidance: "Internal path, e.g. /contact", example: "/contact", source: {"kind":"pageField","path":"hero.ctaUrl"} },
        "backgroundImageUrl": { purpose: "Background image URL", type: "string", required: false, guidance: "High-res photo, 1440px wide minimum", example: "__NO_IMAGE__", source: {"kind":"pageField","path":"hero.backgroundImageUrl"} }
      },
    },
    "FeatureGridEvenFeatureGrid": {
      component: "FeatureGridEvenFeatureGrid",
      purpose: "feature-grid — feature-grid-even layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"features"} }
      },
    },
    "ProgramCardsSticky": {
      component: "ProgramCardsSticky",
      purpose: "feature-grid — program-cards-sticky layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"programs"} }
      },
    }
  },
  pages: {
    "home": {
      path: "/",
      archetype: "home",
      components: ["Unknown","HeroCenter","ProgramCardsSticky","Unknown","FeatureGridEven","MediaBlock","FeatureGridEven","FeatureGridEvenFeatureGrid","TestimonialBand","FeatureGridEven","FeatureGridEvenFeatureGrid","MediaBlock","LocationBlock"],
    },
    "about": {
      path: "/about",
      archetype: "about",
      components: ["Unknown"],
    },
    "contact": {
      path: "/contact",
      archetype: "contact",
      components: ["Unknown"],
    },
    "pricing": {
      path: "/pricing",
      archetype: "pricing",
      components: ["Unknown"],
    },
    "schedule": {
      path: "/schedule",
      archetype: "schedule",
      components: ["Unknown"],
    },
    "programIndex": {
      path: "/programs",
      archetype: "programIndex",
      components: ["Unknown"],
    },
    "program": {
      path: "/programs/:slug",
      archetype: "program",
      components: ["Unknown"],
    },
    "blog": {
      path: "/blog",
      archetype: "blogIndex",
      components: ["Unknown"],
    },
    "legal": {
      path: "/legal",
      archetype: "content",
      components: ["Unknown"],
    }
  },
};
