// Auto-generated by milo template pipeline — review and enrich before shipping.
import type { TemplateSpec } from "./types.js";

export const modernSpec: TemplateSpec = {
  name: "modern",
  description: "Auto-generated from modern reference site.",
  headAssets: [
    // Source site Webflow CSS — styles all Webflow class names used in adapted components
    { tag: "link", attrs: { rel: "stylesheet", href: "https://cdn.prod.website-files.com/63caaac34d6a35f37e074c09/css/pushpress-site-modern.shared.cb137d268.min.css" } },
    // Google Fonts used by the source template
    { tag: "link", attrs: { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800;900&family=Barlow:wght@400;600;700&display=swap" } },
    // Brand token overrides — must come AFTER Webflow CSS to win cascade
    { tag: "link", attrs: { rel: "stylesheet", href: "/styles/modern.css" } },
  ],
  bodyClasses: ["bg-white"],
  sections: {},
  components: {
    "CtaBand": {
      component: "CtaBand",
      purpose: "cta-band — large centered CTA text between sections",
      props: {
        "headline": { purpose: "Large centered CTA headline", type: "string", required: false, guidance: "Bold outcome-focused statement", example: "Every Body Is Unique. Find Something That Works For You", source: { kind: "pageField", path: "programsHeadline" } },
        "ctaText": { purpose: "CTA button label", type: "string", required: false, guidance: "2-4 words", example: "View All Programs", source: { kind: "pageField", path: "hero.ctaLabel" } },
        "ctaHref": { purpose: "CTA button URL", type: "string", required: false, guidance: "Internal path", example: "/programs", source: { kind: "pageField", path: "hero.ctaUrl" } },
      },
    },
    "DarkFeatureGrid": {
      component: "DarkFeatureGrid",
      purpose: "dark-feature-grid — dark navy section with icon cards",
      props: {
        "headline": { purpose: "Section headline", type: "string", required: false, guidance: "Bold feature-focused headline", example: "Everything You Need To Crush Your Fitness Goals", source: { kind: "pageField", path: "trustHeadline" } },
        "items": { purpose: "Feature items with icon and label", type: "object", required: false, guidance: "6 items", example: "[]", source: { kind: "computed", fn: "features" } },
      },
    },
    "Unknown": {
      component: "Unknown",
      purpose: "unknown — unknown layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} }
      },
    },
    "FeatureGridEven": {
      component: "FeatureGridEven",
      purpose: "content-block — feature-grid-even layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"features"} }
      },
    },
    "HeroCenter": {
      component: "HeroCenter",
      purpose: "hero — hero-center layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "subheadline": { purpose: "Supporting subtitle text", type: "string", required: false, guidance: "1-2 sentences, expand on the headline", example: "Join our community and reach your goals.", source: {"kind":"pageField","path":"hero.subheading"} },
        "ctaText": { purpose: "Call-to-action button label", type: "string", required: false, guidance: "2-4 words, imperative verb, low commitment", example: "Book a free class", source: {"kind":"pageField","path":"hero.ctaLabel"} },
        "ctaHref": { purpose: "Call-to-action button URL", type: "string", required: false, guidance: "Internal path, e.g. /contact", example: "/contact", source: {"kind":"pageField","path":"hero.ctaUrl"} },
        "backgroundImageUrl": { purpose: "Background image URL", type: "string", required: false, guidance: "High-res photo, 1440px wide minimum", example: "__NO_IMAGE__", source: {"kind":"pageField","path":"hero.backgroundImageUrl"} }
      },
    },
    "FeatureGridEvenFeatureGrid": {
      component: "FeatureGridEvenFeatureGrid",
      purpose: "feature-grid — feature-grid-even layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"features"} }
      },
    },
    "ProgramCardsSticky": {
      component: "ProgramCardsSticky",
      purpose: "feature-grid — program-cards-sticky layout",
      props: {
        "headline": { purpose: "Main heading text", type: "string", required: true, guidance: "3-8 words, outcome-focused, active voice", example: "Transform Your Life", source: {"kind":"pageField","path":"hero.headline"} },
        "items": { purpose: "Array of content items for this section", type: "object", required: false, guidance: "2-6 items, each with a title and description", example: "[]", source: {"kind":"computed","fn":"programs"} }
      },
    }
  },
  pages: {
    "home": {
      path: "/",
      archetype: "home",
      // Source order: hero → hero-cards → programs → testimonial → location
      components: [
        "HeroCenter",           // full-bleed hero with athlete photo + CTA
        "ContentBlock",         // "Feel Supported / Have Fun / Varied Workouts" cards (adapted)
        "FeatureGridEven",      // programs: Bootcamp / Personal Training / Strength & Stretch (adapted)
        "TestimonialBand",      // testimonials (adapted)
        "LocationBlock",        // location/contact (adapted)
      ],
    },
    "about": {
      path: "/about",
      archetype: "about",
      components: ["Unknown"],
    },
    "contact": {
      path: "/contact",
      archetype: "contact",
      components: ["Unknown"],
    },
    "pricing": {
      path: "/pricing",
      archetype: "pricing",
      components: ["Unknown"],
    },
    "schedule": {
      path: "/schedule",
      archetype: "schedule",
      components: ["Unknown"],
    },
    "programIndex": {
      path: "/programs",
      archetype: "programIndex",
      components: ["Unknown"],
    },
    "program": {
      path: "/programs/:slug",
      archetype: "program",
      components: ["Unknown"],
    },
    "blog": {
      path: "/blog",
      archetype: "blogIndex",
      components: ["Unknown"],
    },
    "legal": {
      path: "/legal",
      archetype: "content",
      components: ["Unknown"],
    }
  },
};
