// Auto-generated by milo adapt stage — review before shipping.
import type { AstroComponent } from "../../../lib/template-resolver";

import ClosureBlock from "../ClosureBlock.astro";
import Amenities from "./Amenities.astro";
import CTABand from "./CTABand.astro";
import Community from "./Community.astro";
import ContentBlock from "./ContentBlock.astro";
import CoreValues from "./CoreValues.astro";
import FAQ from "./FAQ.astro";
import FeatureGrid from "./FeatureGrid.astro";
import FeatureGridEven from "./FeatureGridEven.astro";
import Hero from "./Hero.astro";
import HeroCenter from "./HeroCenter.astro";
import HowItWorks from "./HowItWorks.astro";
import Location from "./Location.astro";
import LocationBlock from "./LocationBlock.astro";
import MediaBlock from "./MediaBlock.astro";
import ProgramCardsSticky from "./ProgramCardsSticky.astro";
import Programs from "./Programs.astro";
import TestimonialBand from "./TestimonialBand.astro";
import Testimonials from "./Testimonials.astro";
import Unknown from "./Unknown.astro";

export const COMPONENT_MAP: Record<string, AstroComponent> = {
  "ClosureBlock": ClosureBlock as unknown as AstroComponent,
  "closureBlock": ClosureBlock as unknown as AstroComponent,
  "Amenities": Amenities as unknown as AstroComponent,
  "CTABand": CTABand as unknown as AstroComponent,
  "Community": Community as unknown as AstroComponent,
  "ContentBlock": ContentBlock as unknown as AstroComponent,
  "CoreValues": CoreValues as unknown as AstroComponent,
  "FAQ": FAQ as unknown as AstroComponent,
  "FeatureGrid": FeatureGrid as unknown as AstroComponent,
  "FeatureGridEven": FeatureGridEven as unknown as AstroComponent,
  "Hero": Hero as unknown as AstroComponent,
  "HeroCenter": HeroCenter as unknown as AstroComponent,
  "HowItWorks": HowItWorks as unknown as AstroComponent,
  "Location": Location as unknown as AstroComponent,
  "LocationBlock": LocationBlock as unknown as AstroComponent,
  "MediaBlock": MediaBlock as unknown as AstroComponent,
  "ProgramCardsSticky": ProgramCardsSticky as unknown as AstroComponent,
  "Programs": Programs as unknown as AstroComponent,
  "TestimonialBand": TestimonialBand as unknown as AstroComponent,
  "Testimonials": Testimonials as unknown as AstroComponent,
  "Unknown": Unknown as unknown as AstroComponent,
};
