// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import type { ComponentResult } from "../../types/pipeline-artifacts";
import type { TemplateDocs } from "./doc-writer";

export interface ScaffoldInput {
  templateName: string;
  components: ComponentResult[];
  specSource: string;
  docs: TemplateDocs;
  cssSource: string;
  repoRoot: string;
}

export interface ScaffoldPaths {
  componentsDir: string;
  specFile: string;
  docsDir: string;
  cssFile: string;
}

export function scaffoldTemplate(input: ScaffoldInput): ScaffoldPaths {
  const { templateName: name, repoRoot } = input;

  const componentsDir = path.join(repoRoot, "apps/renderer/src/components/sections", name);
  const specFile = path.join(repoRoot, "packages/shared-types/src/templates", `${name}.ts`);
  const docsDir = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", name);
  const cssFile = path.join(repoRoot, "apps/renderer/public/styles", `${name}.css`);
  const docLoaderFile = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", `${name}.ts`);

  fs.mkdirSync(componentsDir, { recursive: true });
  for (const c of input.components) {
    fs.writeFileSync(path.join(componentsDir, `${c.name}.astro`), c.code, "utf8");
  }

  fs.writeFileSync(path.join(componentsDir, "index.ts"), buildComponentIndex(name, input.components), "utf8");

  fs.writeFileSync(cssFile, input.cssSource, "utf8");
  fs.writeFileSync(specFile, input.specSource, "utf8");

  fs.mkdirSync(docsDir, { recursive: true });
  fs.writeFileSync(path.join(docsDir, "personality.md"), input.docs.personality, "utf8");
  fs.writeFileSync(path.join(docsDir, "components.md"), input.docs.components, "utf8");
  fs.writeFileSync(path.join(docsDir, "page-archetypes.md"), input.docs.pageArchetypes, "utf8");
  fs.writeFileSync(docLoaderFile, buildDocLoader(name), "utf8");

  patchRegistry(path.join(repoRoot, "packages/shared-types/src/templates/registry.ts"), name);
  patchTemplateTypes(path.join(repoRoot, "packages/shared-types/src/templates/types.ts"), name);
  patchPackageIndex(path.join(repoRoot, "packages/shared-types/src/index.ts"), name);

  return { componentsDir, specFile, docsDir, cssFile };
}

function buildComponentIndex(name: string, components: ComponentResult[]): string {
  const imports = components
    .map((c) => `import ${c.name} from "./${c.name}.astro";`)
    .join("\n");
  const entries = components
    .map((c) => `  "${c.name}": ${c.name} as unknown as AstroComponent,`)
    .join("\n");
  return `// Auto-generated by milo template pipeline.
import type { AstroComponent } from "../../../lib/template-resolver";

${imports}

export const COMPONENT_MAP: Record<string, AstroComponent> = {
${entries}
};
`;
}

function buildDocLoader(name: string): string {
  return `// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const dir = path.join(path.dirname(fileURLToPath(import.meta.url)), "${name}");
export const ${name}Docs = {
  personality: fs.readFileSync(path.join(dir, "personality.md"), "utf8"),
  components: fs.readFileSync(path.join(dir, "components.md"), "utf8"),
  pageArchetypes: fs.readFileSync(path.join(dir, "page-archetypes.md"), "utf8"),
};
`;
}

export function applyRegistryPatch(src: string, name: string): string {
  if (src.includes(`from "./${name}.js"`)) return src; // already patched
  const withImport = src.replace(/^((?:import .+;\n)+)/m, `$1import { ${name}Spec } from "./${name}.js";\n`);
  if (withImport === src) {
    throw new Error(`[code-scaffolder] patchRegistry: failed to find import block`);
  }
  const withEntry = withImport.replace(
    /(\n(\s+)\S.+,\n)(\};)/,
    `$1$2${name}: ${name}Spec,\n$3`,
  );
  if (withEntry === withImport) {
    throw new Error(`[code-scaffolder] patchRegistry: failed to find insertion point`);
  }
  return withEntry;
}

function patchRegistry(registryPath: string, name: string): void {
  const src = fs.readFileSync(registryPath, "utf8");
  fs.writeFileSync(registryPath, applyRegistryPatch(src, name), "utf8");
}

function patchPackageIndex(indexPath: string, name: string): void {
  const src = fs.readFileSync(indexPath, "utf8");
  if (src.includes(`from "./templates/${name}.js"`)) return; // already patched

  const withExport = src.replace(
    /(export \{ beanburitoSpec, buildSpecPrompt, buildPageSpecPrompt \} from "\.\/templates\/beanburito\.js";\n)/,
    `$1export { ${name}Spec } from "./templates/${name}.js";\n`,
  );
  if (withExport === src) {
    throw new Error(`[code-scaffolder] patchPackageIndex: failed to find beanburito export anchor in ${indexPath}`);
  }

  fs.writeFileSync(indexPath, withExport, "utf8");
}

export function applyTypesPatch(src: string, name: string): string {
  if (src.includes(`"${name}"`)) return src; // already patched
  const withUnion = src.replace(
    /(export type TemplateTheme = (?:"[^"]*"(?: \| "[^"]*")*));/,
    `$1 | "${name}";`,
  );
  if (withUnion === src) {
    throw new Error(`[code-scaffolder] patchTemplateTypes: failed to find TemplateTheme union`);
  }
  const withArray = withUnion.replace(
    /(TEMPLATE_THEMES: TemplateTheme\[\] = \[[^\]]+)(\];)/,
    `$1, "${name}"$2`,
  );
  if (withArray === withUnion) {
    throw new Error(`[code-scaffolder] patchTemplateTypes: failed to find TEMPLATE_THEMES array`);
  }
  return withArray;
}

function patchTemplateTypes(typesPath: string, name: string): void {
  const src = fs.readFileSync(typesPath, "utf8");
  fs.writeFileSync(typesPath, applyTypesPatch(src, name), "utf8");
}
