// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import type { ComponentResult } from "../../types/pipeline-artifacts";
import type { TemplateDocs } from "./doc-writer";

export interface ScaffoldInput {
  templateName: string;
  components: ComponentResult[];
  specSource: string;
  docs: TemplateDocs;
  cssSource: string;
  repoRoot: string;
}

export interface ScaffoldPaths {
  componentsDir: string;
  specFile: string;
  docsDir: string;
  cssFile: string;
}

export function scaffoldTemplate(input: ScaffoldInput): ScaffoldPaths {
  const { templateName: name, repoRoot } = input;

  const componentsDir = path.join(repoRoot, "apps/renderer/src/components/sections", name);
  const specFile = path.join(repoRoot, "packages/shared-types/src/templates", `${name}.ts`);
  const docsDir = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", name);
  const cssFile = path.join(repoRoot, "apps/renderer/public/styles", `${name}.css`);
  const docLoaderFile = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", `${name}.ts`);

  fs.mkdirSync(componentsDir, { recursive: true });
  for (const c of input.components) {
    fs.writeFileSync(path.join(componentsDir, `${c.name}.astro`), c.code, "utf8");
  }

  fs.writeFileSync(cssFile, input.cssSource, "utf8");
  fs.writeFileSync(specFile, input.specSource, "utf8");

  fs.mkdirSync(docsDir, { recursive: true });
  fs.writeFileSync(path.join(docsDir, "personality.md"), input.docs.personality, "utf8");
  fs.writeFileSync(path.join(docsDir, "components.md"), input.docs.components, "utf8");
  fs.writeFileSync(path.join(docsDir, "page-archetypes.md"), input.docs.pageArchetypes, "utf8");
  fs.writeFileSync(docLoaderFile, buildDocLoader(name), "utf8");

  patchRegistry(path.join(repoRoot, "packages/shared-types/src/templates/registry.ts"), name);
  patchTemplateTypes(path.join(repoRoot, "packages/shared-types/src/templates/types.ts"), name);

  return { componentsDir, specFile, docsDir, cssFile };
}

function buildDocLoader(name: string): string {
  return `// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
const dir = path.join(new URL(".", import.meta.url).pathname, "${name}");
export const ${name}Docs = {
  personality: fs.readFileSync(path.join(dir, "personality.md"), "utf8"),
  components: fs.readFileSync(path.join(dir, "components.md"), "utf8"),
  pageArchetypes: fs.readFileSync(path.join(dir, "page-archetypes.md"), "utf8"),
};
`;
}

function patchRegistry(registryPath: string, name: string): void {
  let src = fs.readFileSync(registryPath, "utf8");
  if (src.includes(`from "./${name}"`)) return; // already patched
  // Add import after the last import block (the contiguous block at the top of the file)
  src = src.replace(/^((?:import .+;\n)+)/m, `$1import { ${name}Spec } from "./${name}.js";\n`);
  // Add new entry before the closing `};` of the registry object
  // Matches the last entry line (anything ending with a comma) immediately before `};`
  src = src.replace(/(\n(\s+)\S.+,\n)(\};)/, `$1$2${name}: ${name}Spec,\n$3`);
  fs.writeFileSync(registryPath, src, "utf8");
}

function patchTemplateTypes(typesPath: string, name: string): void {
  let src = fs.readFileSync(typesPath, "utf8");
  if (src.includes(`"${name}"`)) return; // already patched
  // TemplateTheme union: append | "name" before the semicolon
  src = src.replace(
    /(export type TemplateTheme = (?:"[^"]*"(?: \| "[^"]*")*));/,
    `$1 | "${name}";`,
  );
  // TEMPLATE_THEMES array: append before closing ]
  src = src.replace(
    /(TEMPLATE_THEMES: TemplateTheme\[\] = \[[^\]]+)(\];)/,
    `$1, "${name}"$2`,
  );
  fs.writeFileSync(typesPath, src, "utf8");
}
