// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import type { ComponentResult } from "../../types/pipeline-artifacts";
import type { TemplateDocs } from "./doc-writer";

export interface ScaffoldInput {
  templateName: string;
  components: ComponentResult[];
  specSource: string;
  docs: TemplateDocs;
  cssSource: string;
  repoRoot: string;
}

export interface ScaffoldPaths {
  componentsDir: string;
  specFile: string;
  docsDir: string;
  cssFile: string;
}

export function scaffoldTemplate(input: ScaffoldInput): ScaffoldPaths {
  const { templateName: name, repoRoot } = input;

  const componentsDir = path.join(repoRoot, "apps/renderer/src/components/sections", name);
  const specFile = path.join(repoRoot, "packages/shared-types/src/templates", `${name}.ts`);
  const docsDir = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", name);
  const cssFile = path.join(repoRoot, "apps/renderer/public/styles", `${name}.css`);
  const docLoaderFile = path.join(repoRoot, "apps/api/src/ai/prompts/site-templates", `${name}.ts`);

  fs.mkdirSync(componentsDir, { recursive: true });
  for (const c of input.components) {
    fs.writeFileSync(path.join(componentsDir, `${c.name}.astro`), c.code, "utf8");
  }

  fs.writeFileSync(cssFile, input.cssSource, "utf8");
  fs.writeFileSync(specFile, input.specSource, "utf8");

  fs.mkdirSync(docsDir, { recursive: true });
  fs.writeFileSync(path.join(docsDir, "personality.md"), input.docs.personality, "utf8");
  fs.writeFileSync(path.join(docsDir, "components.md"), input.docs.components, "utf8");
  fs.writeFileSync(path.join(docsDir, "page-archetypes.md"), input.docs.pageArchetypes, "utf8");
  fs.writeFileSync(docLoaderFile, buildDocLoader(name), "utf8");

  patchRegistry(path.join(repoRoot, "packages/shared-types/src/templates/registry.ts"), name);
  patchTemplateTypes(path.join(repoRoot, "packages/shared-types/src/templates/types.ts"), name);

  return { componentsDir, specFile, docsDir, cssFile };
}

function buildDocLoader(name: string): string {
  return `// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const dir = path.join(path.dirname(fileURLToPath(import.meta.url)), "${name}");
export const ${name}Docs = {
  personality: fs.readFileSync(path.join(dir, "personality.md"), "utf8"),
  components: fs.readFileSync(path.join(dir, "components.md"), "utf8"),
  pageArchetypes: fs.readFileSync(path.join(dir, "page-archetypes.md"), "utf8"),
};
`;
}

function patchRegistry(registryPath: string, name: string): void {
  let src = fs.readFileSync(registryPath, "utf8");
  if (src.includes(`from "./${name}"`)) return; // already patched

  const withImport = src.replace(/^((?:import .+;\n)+)/m, `$1import { ${name}Spec } from "./${name}.js";\n`);
  if (withImport === src) {
    throw new Error(`[code-scaffolder] patchRegistry: failed to find import block in ${registryPath}`);
  }

  const withEntry = withImport.replace(
    /(\n(\s+)\S.+,\n)(\};)/,
    `$1$2${name}: ${name}Spec,\n$3`,
  );
  if (withEntry === withImport) {
    throw new Error(`[code-scaffolder] patchRegistry: failed to find insertion point in ${registryPath}`);
  }

  fs.writeFileSync(registryPath, withEntry, "utf8");
}

function patchTemplateTypes(typesPath: string, name: string): void {
  let src = fs.readFileSync(typesPath, "utf8");
  if (src.includes(`"${name}"`)) return; // already patched

  const withUnion = src.replace(
    /(export type TemplateTheme = (?:"[^"]*"(?: \| "[^"]*")*));/,
    `$1 | "${name}";`,
  );
  if (withUnion === src) {
    throw new Error(`[code-scaffolder] patchTemplateTypes: failed to find TemplateTheme union in ${typesPath}`);
  }

  const withArray = withUnion.replace(
    /(TEMPLATE_THEMES: TemplateTheme\[\] = \[[^\]]+)(\];)/,
    `$1, "${name}"$2`,
  );
  if (withArray === withUnion) {
    throw new Error(`[code-scaffolder] patchTemplateTypes: failed to find TEMPLATE_THEMES array in ${typesPath}`);
  }

  fs.writeFileSync(typesPath, withArray, "utf8");
}
