// Auto-generated spec writer for Milo template pipeline.
import type { ComponentGroup } from "./section-grouper";

const VALID_ARCHETYPES = new Set([
  "home",
  "program",
  "programIndex",
  "about",
  "contact",
  "schedule",
  "pricing",
  "blogIndex",
  "blogPost",
  "content",
  "team",
  "form",
]);

const KNOWN_ARCHETYPES: Record<string, string> = {
  "/": "home",
  "/about": "about",
  "/contact": "contact",
  "/pricing": "pricing",
  "/schedule": "schedule",
};

export function generateTemplateSpecSource(
  name: string,
  groups: ComponentGroup[],
  pageMap: Record<string, string[]>,
): string {
  const componentsBlock = groups
    .map(
      (g) => `    "${g.name}": {
      component: "${g.name}",
      purpose: "${g.tag} — ${g.archetype} layout",
      props: {},
    }`,
    )
    .join(",\n");

  const pagesBlock = Object.entries(pageMap)
    .map(([p, components]) => {
      const key =
        p === "/"
          ? "home"
          : p.replace(/^\//, "").replace(/\//g, "-") || "home";
      const derived = KNOWN_ARCHETYPES[p] ?? key.split("-")[0] ?? "content";
      const archetype = VALID_ARCHETYPES.has(derived) ? derived : "content";
      return `    "${key}": {
      path: "${p}",
      archetype: "${archetype}",
      components: ${JSON.stringify(components)},
    }`;
    })
    .join(",\n");

  return `// Auto-generated by milo template pipeline — review and enrich before shipping.
import type { TemplateSpec } from "./types.js";

export const ${name}Spec: TemplateSpec = {
  name: "${name}",
  description: "Auto-generated from ${name} reference site.",
  sections: {},
  components: {
${componentsBlock}
  },
  pages: {
${pagesBlock}
  },
};
`;
}
