// Auto-generated by milo template pipeline.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const dir = path.join(path.dirname(fileURLToPath(import.meta.url)), "modern");
export const modernDocs = {
  personality: fs.readFileSync(path.join(dir, "personality.md"), "utf8"),
  components: fs.readFileSync(path.join(dir, "components.md"), "utf8"),
  pageArchetypes: fs.readFileSync(path.join(dir, "page-archetypes.md"), "utf8"),
};
